id = "gsczed"
name = "GSC Language Server"
version = "0.0.1"
schema_version = 1
authors = ["echo000"]
description = "GSC and CSC Language Server for Zed"
repository = "https://github.com/echo000/gscode-zed"

[grammars.gsc]
repository = "https://github.com/echo000/tree-sitter-gsc"
rev = "58d362e1777d57a2bb86e5de4f0884f5dff4db05"

[language_servers.gscode]
name = "GSCode Language Server"
languages = ["GSC", "CSC", "GSH"]
